blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('post/create/', views.CreatePost.as_view(), name="create-post"),
    path('post/retrieve/<int:pk>/', views.RetrievePost.as_view(), name="retrieve-post"),
    path('post/update/<int:pk>/', views.UpdatePost.as_view(
        success_url='/blog/post/retrieve/%(pk)/'), name="update-post"),
    path('post/delete/<int:pk>/', views.DeletePost.as_view(), name="delete-post"),
    path('st/', views.StaticView.as_view(), name="static-template"),
]

grundlagen/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from grundlagen import settings

urlpatterns = [
    path('', lambda x: redirect('/blog/')),
    path('blog/', include('blog.urls', 'blog')),
    path('videos/', include('yourvid.urls', 'yourvid')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourvid/urls.py
from django.urls import path

from . import views

app_name = 'yourvid'
urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<str:video_id>/', views.detail_view, name="detail"),
    path('comment/add/<str:video_id>/', views.comment_add, name="add-comment"),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_date = models.DateTimeField()

    def __str__(self):
        return f"#{self.id} - {self.title}"

    def word_count(self):
        return len(self.text.split())

    class Meta:
        permissions: [
            ('publish_blogpost', 'Publish Blogposts.'),
        ]

blog/forms.py
from django import forms

from blog.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

blog/api/views.py
from rest_framework.mixins import (
    ListModelMixin, RetrieveModelMixin, UpdateModelMixin, CreateModelMixin, DestroyModelMixin
)
from rest_framework.viewsets import GenericViewSet

from .serializers import BlogPostSerializer
from ..models import BlogPost


class BlogPostViewSet(CreateModelMixin, RetrieveModelMixin, ListModelMixin,
                      UpdateModelMixin, DestroyModelMixin, GenericViewSet):
    serializer_class = BlogPostSerializer
    queryset = BlogPost.objects.all()

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from blog.models import BlogPost


class IndexView(ListView):
    model = BlogPost
    paginate_by = 2


class StaticView(TemplateView):
    template_name = "blog/static.html"
    extra_context = {
        'my_var': "Ein anderer String"
    }


class CreatePost(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = (
        'title',
        'text',
        'publish_date',
        'author',
    )
    permission_required = ('blog.add_blogpost', )

    def get_success_url(self):
        return reverse('blog:retrieve-post', kwargs={'pk': self.object.pk})
        # alternative with args
        # return reverse('blog:retrieve-post', args=[self.object.pk])


class RetrievePost(DetailView):
    model = BlogPost


class UpdatePost(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = (
        'title',
        'text',
    )
    permission_required = ('blog.change_blogpost', )

    def get_success_url(self):
        return reverse('blog:retrieve-post', kwargs={'pk': self.object.pk})


class DeletePost(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:index')
    permission_required = ('blog.delete_blogpost', )

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
Are you sure, you want to delete this post?
<form action="{% url 'blog:delete-post' object.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Delete Post</button>
</form>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}

{% block content %}
{% include 'blog/blogpost_single.html' %}
<p>{{ object.text }}</p>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sumbit</button>
</form>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'base.html' %}

{% block content %}
{% for object in object_list %}
{% include 'blog/blogpost_single.html' %}
{% if object_list.count > 1 %}
<hr>
{% endif %}
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

blog/templates/blog/blogpost_single.html
<h1><a href="{% url 'blog:retrieve-post' object.pk %}">{{ object.title }}</a></h1>
<small>{{ object.publish_date }}</small>

blog/templates/blog/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>Contact Form</h1>
<form action="{% url 'blog:contact' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Wech damit!</button>
</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}Blog | Detail{% endblock %}}

{% block content %}
    <h1>Blog Posts</h1>
    {% for blogpost in blogposts %}
    <article>
        <h2>{{ blogpost.title }}</h2>
        <i>Posted {{ blogpost.date_created }}</i>
        <div>
            {{ blogpost.text }}
        </div>
    </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Blog | Index{% endblock %}}

{% block content %}
    <h1>Blog Posts</h1>
    {% for blogpost in blogposts %}
    <article>
        <h2>
            <a href="{% url 'blog:detail' blogpost.id %}">
                {{ blogpost.title }}</a>
        </h2>
        <i>Posted {{ blogpost.date_created }}</i>
        <div>
            {{ blogpost.text | truncatewords:50 }}
        </div>
    </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/static.html
{% extends 'base.html' %}

{% block content %}
<h1>This is a static page.</h1>
<p>Context: <strong>{{ my_var }}</strong></p>
{% endblock %}