blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('post/create/', views.CreatePost.as_view(), name="create-post"),
    path('post/retrieve/<int:pk>/', views.RetrievePost.as_view(), name="retrieve-post"),
    path('post/update/<int:pk>/', views.UpdatePost.as_view(
        success_url='/blog/post/retrieve/%(pk)/'), name="update-post"),
    path('post/delete/<int:pk>/', views.DeletePost.as_view(), name="delete-post"),
    path('st/', views.StaticView.as_view(), name="static-template"),
]

grundlagen/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from grundlagen import settings

urlpatterns = [
    path('', lambda x: redirect('/blog/')),
    path('blog/', include('blog.urls', 'blog')),
    path('videos/', include('yourvid.urls', 'yourvid')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourvid/urls.py
from django.urls import path

from . import views

app_name = 'yourvid'
urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<str:video_id>/', views.detail_view, name="detail"),
    path('comment/add/<str:video_id>/', views.comment_add, name="add-comment"),
]

templates/base.html
{% load static %}
<html lang="de">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}
        My Page
        {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% block scripts_early %}
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-brand"><img src="{% static "img/logo.png" %}" height="45px" /></div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% block navbar %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'yourvid:index' %}">Videos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
                    </li>
                </ul>
                {% endblock %}
            </div>
        </nav>
    </header>

    <main>
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
                class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        {% endfor %}
        {% endif %}
        <div class="main container">
            {% block content %}
            Testcontent
            {% endblock %}
        </div>
    </main>

    <footer class="page-footer font-small blue pt-4">
        {% block footer %}
        <div class="footer-copyright text-center py-3">© 2020 Copyright:
            <a href="https://schliesky.com/"> schliesky.com</a>
        </div>
        {% endblock %}
    </footer>

    {% block scripts_late %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    {% endblock %}

</body>

</html>