blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('post/create/', views.CreatePost.as_view(), name="create-post"),
    path('post/retrieve/<int:pk>/', views.RetrievePost.as_view(), name="retrieve-post"),
    path('post/update/<int:pk>/', views.UpdatePost.as_view(
        success_url='/blog/post/retrieve/%(pk)/'), name="update-post"),
    path('post/delete/<int:pk>/', views.DeletePost.as_view(), name="delete-post"),
    path('st/', views.StaticView.as_view(), name="static-template"),
]

grundlagen/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

from grundlagen import settings

urlpatterns = [
    path('', lambda x: redirect('/blog/')),
    path('blog/', include('blog.urls', 'blog')),
    path('videos/', include('yourvid.urls', 'yourvid')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourvid/urls.py
from django.urls import path

from . import views

app_name = 'yourvid'
urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<str:video_id>/', views.detail_view, name="detail"),
    path('comment/add/<str:video_id>/', views.comment_add, name="add-comment"),
]

yourvid/models.py
from django.contrib.auth.models import User
from django.db import models
from django_extensions.db.fields import AutoSlugField

from yourvid.helpers import generate_random_string, video_upload_path, random_video_id, thumbnail_upload_path

LANGUAGE_CHOICES = (
    ('DE', 'Deutsch'),
    ('EN', 'English'),
    ('FR', 'French'),
    ('RU', 'Russian'),
)

ACCESS_CHOICES = (
    ('PUBLIC', 'Public'),
    ('NOTLISTED', 'Not Listed'),
    ('PRIVATE', 'Private'),
)


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from=['name'])

    def __str__(self):
        return self.name


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='votes')
    video = models.ForeignKey('Video', on_delete=models.CASCADE, related_name='ratings')
    score = models.IntegerField(default=0)


class Video(models.Model):
    video_id = models.CharField(max_length=14, default=random_video_id, unique=True)
    language = models.CharField(max_length=3, choices=LANGUAGE_CHOICES)
    title = models.CharField(max_length=255)
    video_file = models.FileField(upload_to=video_upload_path)
    upload_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    thumbnail = models.ImageField(upload_to=thumbnail_upload_path)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    access = models.CharField(max_length=255, choices=ACCESS_CHOICES)

    # create format to show in the video_id and title
    def __str__(self):
        return f"{self.video_id}-{self.title}"

    def rating(self):
        """
        (int) Returns the sum of all voted scores on this Video.
        """
        ratings = self.ratings.all()
        score = 0
        for rating in ratings:
            score += rating.score
        return score


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"#{self.id} - {self.user.username} commented on {self.video.title}"

yourvid/forms.py
from django import forms


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

yourvid/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from yourvid.forms import CommentForm
from yourvid.models import Category, Video, Comment


# Create your views here.


def index(request):
    all_categories = Category.objects.all()
    latest_videos = Video.objects.order_by('-upload_date')[0:20]
    context = {
        'categories': all_categories,
        'videos': latest_videos,
    }
    return render(request, 'yourvid/index.html', context=context)


@login_required
def detail_view(request, video_id):
    video = Video.objects.get(video_id=video_id)
    context = {
        'video': video,
        'form': CommentForm()
    }
    return render(request, 'yourvid/detail.html', context=context)


def comment_add(request, video_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        video = Video.objects.get(video_id=video_id)
        if form.is_valid():
            Comment.objects.create(
                user=request.user,
                text=form.cleaned_data["text"],
                video=video,
            )
            return redirect('yourvid:detail', video_id)
    return redirect('yourvid:index')

yourvid/templates/yourvid/detail.html
{% extends 'base.html' %}

{% block title %}Yourvid | Detail{% endblock %}}

{% block content %}
<video width="80%" controls>
  <source src="{{ video.video_file.url }}">
  Your browser does not support the video tag.
</video>
<h3>{{ video.title }}</h3>
<p>{{ video.description }}</p>

<form action="{% url 'yourvid:add-comment' video.video_id %}" method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="hidden" name="video_id" value="{{ video.video_id }}">
  <button type="submit" class="btn btn-success">Comment</button>
</form>

{% for comment in video.comments.all %}
    <div class="comment">
      {{ comment.user.username }}
      <br>
      {{ comment.text }}
    </div>
    <hr>
{% endfor %}
{% endblock %}

yourvid/templates/yourvid/index.html
{% extends 'base.html' %}

{% block title %}Yourvid | Index{% endblock %}}

{% block content %}
{% for video in videos %}
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="{% url 'yourvid:detail' video.video_id %}"><img src="{{ video.thumbnail.url }}" class="card-img-top"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{ video.title }}</h5>
          <p class="card-text">{{ video.description | truncatewords:50 }}</p>
          <p class="card-text"><small class="text-muted">{{ video.upload_date }}</small></p>
        </div>
      </div>
    </div>
  </div>
{% empty %}
No Videos found.
{% endfor %}
{% endblock %}